apiVersion: batch/v1
kind: Job
metadata:
  name: ml-audio-classification-single-experiment
  namespace: ml-audio-classification
  labels:
    app: ml-audio-classification
    job-type: single-experiment
spec:
  template:
    metadata:
      labels:
        app: ml-audio-classification
        job-type: single-experiment
    spec:
      containers:
      - name: ml-audio-classification
        image: ml-audio-classification:latest
        imagePullPolicy: IfNotPresent
        
        # Environment variables from ConfigMap and Secret
        envFrom:
        - configMapRef:
            name: ml-audio-classification-config
        - secretRef:
            name: ml-audio-classification-secrets
        
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: "/app/credentials/gcp-key.json"
        - name: PYTHONPATH
          value: "/app/src"
        - name: PYTHONUNBUFFERED
          value: "1"
        
        # Resource limits and requests
        resources:
          requests:
            memory: "4Gi"
            cpu: "2"
          limits:
            memory: "8Gi"
            cpu: "4"
        
        # Volume mounts
        volumeMounts:
        - name: data-volume
          mountPath: /app/data
        - name: results-volume
          mountPath: /app/results
        - name: gcp-credentials
          mountPath: /app/credentials
          readOnly: true
        
        # Job command - customize for your experiment
        command: ["python", "-m", "ml_audio_classification", "run-experiment"]
        args: 
        - "--models"
        - "random_forest"
        - "vgg"
        - "--species"
        - "Turdus migratorius"
        - "--training-sizes"
        - "100"
        - "500"
        - "1000"
        - "--cv-folds"
        - "5"
        - "--output-dir"
        - "/app/results"
      
      # Volumes
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: ml-audio-classification-data
      - name: results-volume
        persistentVolumeClaim:
          claimName: ml-audio-classification-results
      - name: gcp-credentials
        secret:
          secretName: ml-audio-classification-secrets
          items:
          - key: GCP_SERVICE_ACCOUNT_KEY
            path: gcp-key.json
      
      # Security context
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      
      restartPolicy: Never
  
  # Job completion settings
  backoffLimit: 3  # Number of retries
  ttlSecondsAfterFinished: 86400  # Clean up after 24 hours
---
apiVersion: batch/v1
kind: Job
metadata:
  name: ml-audio-classification-grid-search
  namespace: ml-audio-classification
  labels:
    app: ml-audio-classification
    job-type: grid-search
spec:
  template:
    metadata:
      labels:
        app: ml-audio-classification
        job-type: grid-search
    spec:
      containers:
      - name: ml-audio-classification
        image: ml-audio-classification:latest
        imagePullPolicy: IfNotPresent
        
        # Environment variables from ConfigMap and Secret
        envFrom:
        - configMapRef:
            name: ml-audio-classification-config
        - secretRef:
            name: ml-audio-classification-secrets
        
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: "/app/credentials/gcp-key.json"
        - name: PYTHONPATH
          value: "/app/src"
        - name: PYTHONUNBUFFERED
          value: "1"
        
        # Resource limits and requests for intensive grid search
        resources:
          requests:
            memory: "6Gi"
            cpu: "3"
          limits:
            memory: "12Gi"
            cpu: "6"
        
        # Volume mounts
        volumeMounts:
        - name: data-volume
          mountPath: /app/data
        - name: results-volume
          mountPath: /app/results
        - name: gcp-credentials
          mountPath: /app/credentials
          readOnly: true
        
        # Grid search command - customize for your experiment
        command: ["python", "-m", "ml_audio_classification", "grid-search"]
        args: 
        - "--models"
        - "random_forest"
        - "svm"
        - "vgg"
        - "mobilenet"
        - "resnet"
        - "birdnet"
        - "perch"
        - "--species"
        - "Turdus migratorius"
        - "Corvus brachyrhynchos"
        - "--training-sizes"
        - "100"
        - "500"
        - "1000"
        - "2000"
        - "--cv-folds"
        - "5"
        - "--output-dir"
        - "/app/results"
        - "--max-concurrent"
        - "3"
      
      # Volumes
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: ml-audio-classification-data
      - name: results-volume
        persistentVolumeClaim:
          claimName: ml-audio-classification-results
      - name: gcp-credentials
        secret:
          secretName: ml-audio-classification-secrets
          items:
          - key: GCP_SERVICE_ACCOUNT_KEY
            path: gcp-key.json
      
      # Security context
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      
      restartPolicy: Never
  
  # Job completion settings
  backoffLimit: 1  # Grid search is resource intensive, limit retries
  ttlSecondsAfterFinished: 172800  # Clean up after 48 hours